In [1]:
import numpy as np
import cvxpy as cp

In [30]:
# A - matrix NxM, shift - array len = M
def shift_operator(shift,A):
    N = A.shape[1]
    A_t = A.T
    for i in range(N):
        A_t[i] = np.roll(A_t[i], shift[i])
    return A_t.T

In [31]:
#used for algo2 to shift columns
def shift_operator_c(k,s,A):
    A_t = A.T
    A_t[k] = np.roll(A_t[k], -s)
    return A_t.T

In [32]:
# return indices of max value, algo 2 B matrix 
#maybe extend in case of max is not single


In [261]:
A = np.array([[2,2,2],[0,0,4],[3,3,3]])
shift = [1,1,2,2]

In [262]:
def find_max_index(A):
    return np.unravel_index(np.argmax(A),A.shape)

In [263]:
print(A)

[[2 2 2]
 [0 0 4]
 [3 3 3]]


In [264]:
find_max_index(A)

(1, 2)

In [275]:
def algo_2(A):
    s = 1
    lmbd = np.zeros(A.shape[1])
    while s != 0:
        A_hat = np.fft.fft2(A)
        U, S, V = np.linalg.svd(A_hat)
        u_hat = U[:,0]
        u_hat = np.conjugate(u_hat)
        B = np.abs(np.fft.ifft2(u_hat* A_hat))**2
        k,s = find_max_index(B)
        print(k,s)
        shift_operator_c(k,s,A)
        lmbd[k] += s
    return lmbd

In [276]:
algo_2(A)

2 0


array([0., 0., 0.])

In [268]:
A = np.array([[2,2,2],[0,0,4],[3,3,3]])
shift = [4,0,2]
print(np.linalg.norm(A,ord =2))
print(np.linalg.norm(shift_operator(shift,A), ord =2 ))

6.778338051889763
6.877074382461075


In [189]:
#trash_2
A_hat = np.fft.fft2(A)
U, S, V = np.linalg.svd(A_hat)
U_t = U.T
u_hat = U_t[0].T
u_hat = np.conjugate(u_hat)
B = np.abs(np.fft.ifft2(u_hat * A_hat))**2


In [190]:
def algo_3(A):
    A_hat = np.fft.fft2(A)
    A_hat_abs = np.abs(A_hat)
    B = np.abs(np.fft.ifft2(A_hat_abs * A_hat))**2
    #to be continued
    #3: Set λ to the indices of the maximum values of B in each column and update A ← S−λ A
    # 4: Update λ and A using Algorithm 2 with (12)        
    #(12): uˆ ← |uˆopt| ⊙ phase(uˆ).
    # 5: Update λ and A using Algorithm 2
    # 6: return λ

